# Generated by Django 3.1.7 on 2021-04-18 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 17, 26, 25, 574772)),
        ),
    ]
