# Generated by Django 3.1.7 on 2021-04-18 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210418_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='studentname',
        ),
        migrations.AlterField(
            model_name='order',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 17, 40, 56, 915615), null=True),
        ),
    ]
