# Generated by Django 3.1.7 on 2021-04-18 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210418_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 17, 41, 22, 304573), null=True),
        ),
    ]
